# Generated by Django 5.2.4 on 2025-07-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
